# Generated by Django 5.1 on 2024-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.SmallIntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.SmallIntegerField(max_length=5),
        ),
    ]
