# Generated by Django 5.1 on 2024-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
