# Generated by Django 5.1 on 2024-08-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_reservation_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guests',
            new_name='no_of_guests',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='reservation_date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Inventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Title',
            new_name='title',
        ),
    ]
